source 'https://github.com/CocoaPods/Specs.git'

target 'BRLazyPagedScrollView', :exclusive => true do
  pod "BRLazyPagedScrollView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BRLazyPagedScrollView", :path => "../"

#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
end
